# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VTHkjTYIdlvsCx3yBQMSFXjWFcOlzASt
"""

# Primero, asegurar que pycryptodome está instalado
!pip install pycryptodome -q

# Importar librerías necesarias
import struct
import time
import random
import os
from Crypto.Cipher import ChaCha20_Poly1305


# CLAVE CORREGIDA - 32 bytes exactos

# Opción 1: Clave fija de 32 bytes (para pruebas)
KEY = b'01234567890123456789012345678901'  # 32 bytes exactos

# Opción 2: Generar clave aleatoria (descomentar si quieres)
# KEY = os.urandom(32)

print(f" Clave generada: {len(KEY)} bytes")
print(f"   (hex): {KEY.hex()[:32]}...")


# EMISOR (CubeSAT simulado)

def load_counter():
    """Carga el contador persistente (simulado con archivo)"""
    try:
        with open('counter.bin', 'rb') as f:
            return struct.unpack('I', f.read())[0]
    except:
        return 0

def save_counter(c):
    """Guarda el contador"""
    with open('counter.bin', 'wb') as f:
        f.write(struct.pack('I', c))

def encrypt_telemetry(data):
    """Cifra telemetría con ChaCha20-Poly1305"""
    ctr = load_counter()
    # Nonce de 12 bytes: 4 bytes contador + 8 bytes cero
    nonce = ctr.to_bytes(12, 'little')

    # Crear cipher con clave y nonce
    cipher = ChaCha20_Poly1305.new(key=KEY, nonce=nonce)

    # Cifrar y obtener tag
    ciphertext = cipher.encrypt(data.encode('utf-8'))
    tag = cipher.digest()

    # Incrementar y guardar contador
    save_counter(ctr + 1)

    # Formato: [4 bytes contador][ciphertext][16 bytes tag]
    return ctr.to_bytes(4, 'little') + ciphertext + tag


# RECEPTOR (Estación Terrestre)

last_seen_counter = -1

def decrypt_telemetry(packet):
    """Descifra y verifica telemetría con anti-replay"""
    global last_seen_counter

    if len(packet) < 20:  # Mínimo: 4(ctr) + 0(data) + 16(tag)
        raise ValueError(f"Paquete demasiado corto: {len(packet)} bytes")

    # Extraer contador
    ctr = struct.unpack('I', packet[:4])[0]

    # Anti-replay: rechazar paquetes antiguos o repetidos
    if ctr <= last_seen_counter:
        raise ValueError(f"Ataque de replay detectado! Contador {ctr} <= {last_seen_counter}")

    # Reconstruir nonce
    nonce = ctr.to_bytes(12, 'little')

    # Extraer ciphertext y tag
    ciphertext = packet[4:-16]
    tag = packet[-16:]

    # Descifrar y verificar
    cipher = ChaCha20_Poly1305.new(key=KEY, nonce=nonce)
    plaintext = cipher.decrypt_and_verify(ciphertext, tag)

    # Actualizar último contador válido
    last_seen_counter = ctr

    return plaintext.decode('utf-8')


# SIMULACIÓN DE CANAL ESPACIAL

def simulate_space_channel(packet, ber=0.001, loss_rate=0.05, delay_ms=10):
    """
    Simula condiciones reales del canal espacial

    Parámetros:
    - ber: Bit Error Rate (ej. 0.001 = 0.1% de bits erróneos)
    - loss_rate: Probabilidad de pérdida de paquete
    - delay_ms: Retardo de propagación en milisegundos
    """
    # Simular retardo de propagación
    if delay_ms > 0:
        time.sleep(delay_ms / 1000.0)

    # Pérdida de paquete (por interferencia o mala orientación)
    if random.random() < loss_rate:
        return None

    # Si no hay errores de bit, devolver paquete original
    if ber == 0:
        return packet

    # Aplicar errores de bit
    data = bytearray(packet)
    errors_applied = 0

    for i in range(len(data)):
        # Cada bit tiene probabilidad 'ber' de ser volteado
        # Como trabajamos con bytes, multiplicamos por 8
        if random.random() < ber * 8:
            bit_pos = random.randint(0, 7)
            data[i] ^= (1 << bit_pos)
            errors_applied += 1

    if errors_applied > 0:
        print(f"    Aplicados {errors_applied} errores de bit al paquete")

    return bytes(data)


# PRUEBAS DE VALIDACIÓN

print("\n" + "="*70)
print(" SIMULACIÓN COMPLETA CUBESAT ↔ ESTACIÓN TERRESTRE")
print("="*70)


# PRUEBA 1: Canal perfecto (sin errores)

print("\n PRUEBA 1: Canal perfecto (sin errores)")
print("-"*50)

# Resetear estado
save_counter(0)
last_seen_counter = -1

for i in range(5):
    # Generar telemetría
    telemetry = f"TEMP:{20+i}°C|BAT:{95-i}%|VOLT:{3.7+i*0.05:.2f}V"

    # Cifrar en el CubeSAT
    encrypted = encrypt_telemetry(telemetry)
    print(f"  [{i}] Enviado: {telemetry}")
    print(f"   → Cifrado: {len(encrypted)} bytes (ctr:{i})")

    # Canal ideal
    received = encrypted

    # Descifrar en estación terrestre
    decrypted = decrypt_telemetry(received)
    print(f"   [{i}] Recibido: {decrypted}")
    print(f"    Verificación exitosa\n")


# PRUEBA 2: Canal con ruido (BER realista)

print("\n PRUEBA 2: Canal con ruido (BER 0.1%, pérdidas 5%)")
print("-"*50)

# Resetear estado
save_counter(0)
last_seen_counter = -1

success_count = 0
corrupt_count = 0
lost_count = 0

for i in range(15):
    telemetry = f"ACC_X:{random.randint(-1000,1000)}|GYRO_Z:{random.randint(-500,500)}"

    # Cifrar
    encrypted = encrypt_telemetry(telemetry)

    # Simular canal espacial con errores
    received = simulate_space_channel(encrypted, ber=0.001, loss_rate=0.05)

    if received is None:
        print(f" [{i}] Paquete PERDIDO en el canal")
        lost_count += 1
        continue

    try:
        decrypted = decrypt_telemetry(received)
        print(f" [{i}] Recibido correctamente: {decrypted[:30]}...")
        success_count += 1
    except Exception as e:
        print(f"  [{i}] Paquete CORRUPTO: {str(e)[:60]}")
        corrupt_count += 1

print(f"\n Estadísticas del canal ruidoso:")
print(f"    Éxitos: {success_count}")
print(f"     Corruptos: {corrupt_count}")
print(f"    Perdidos: {lost_count}")
print(f"    Tasa de éxito: {success_count/15*100:.1f}%")


# PRUEBA 3: Anti-replay (seguridad)

print("\n PRUEBA 3: Detección de ataques de replay")
print("-"*50)

# Resetear estado
save_counter(0)
last_seen_counter = -1

# Comando legítimo
legit_cmd = encrypt_telemetry("COMANDO: ACTIVAR_CAMARA")
decrypted = decrypt_telemetry(legit_cmd)
print(f" Comando legítimo recibido: {decrypted}")

# Intentar replay (reenviar mismo paquete)
try:
    replay = decrypt_telemetry(legit_cmd)
    print(f" ERROR CRÍTICO: Replay no detectado!")
except ValueError as e:
    print(f"  REPLAY DETECTADO: {e}")
    print(f"   → El sistema rechazó el comando repetido")


# PRUEBA 4: Integridad (detección de manipulación)

print("\n PRUEBA 4: Detección de manipulación de comandos")
print("-"*50)

# Resetear estado
save_counter(0)
last_seen_counter = -1

# Enviar comando legítimo
cmd = encrypt_telemetry("COMANDO: DESPLEGAR_PANELES")
print(f" Comando original enviado")

# Manipular un bit del paquete (simular atacante)
tampered = bytearray(cmd)
tampered[10] ^= 0x01  # Voltear un bit
tampered = bytes(tampered)

try:
    decrypted = decrypt_telemetry(tampered)
    print(f" ERROR: Paquete manipulado fue aceptado: {decrypted}")
except ValueError as e:
    print(f"  MANIPULACIÓN DETECTADA: {str(e)[:70]}")
    print(f"   → El sistema rechazó el comando corrupto")


# RESUMEN FINAL

print("\n" + "="*70)
print(" RESUMEN DE SEGURIDAD IMPLEMENTADA")
print("="*70)
print(" Cifrado ChaCha20-Poly1305 (AEAD)")
print(" Autenticación con tag de 16 bytes")
print(" Anti-replay por contador monotónico")
print(" Persistencia de estado (simulada con archivo)")
print(" Detección de corrupción por canal ruidoso")
print(" Protección contra manipulación maliciosa")
print(" Simulación de BER realista (0.1%)")
print("="*70)

# Mostrar información técnica
print("\n ESPECIFICACIONES TÉCNICAS:")
print(f"   Algoritmo: ChaCha20-Poly1305")
print(f"   Tamaño de clave: {len(KEY)*8} bits")
print(f"   Tamaño de nonce: 12 bytes (96 bits)")
print(f"   Tamaño de tag: 16 bytes (128 bits)")
print(f"   Overhead por paquete: 20 bytes (4 ctr + 16 tag)")
print(f"   Formato: [counter:4][ciphertext:var][tag:16]")
